version: "3.9"

services:

  server:
    container_name: server
    restart: always
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    depends_on:
      - postgres
      - redis

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
    - 6379:6379

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    restart: always
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
